version: '3.8'

services:
  web_scraper:
    build: .
    container_name: web_scraper_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 